export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 14

HIST_STAMPS="dd/mm/yyyy"

plugins=(git asdf aws zsh-syntax-highlighting colorize command-not-found compleat docker docker-compose mix)

source $ZSH/oh-my-zsh.sh

# Aliases

alias update="sudo pacman -Syyu"
